In [126]:
## TRABALHO 13 TOTONINE
## f(x)=a0+a1(x−x0)+a2(x−x0)(x−x1)+⋯+an(x−x0)(x−x1)…(x−xn)
## por exemplo f(x0) = a0 = y0
## f(x1) = a0 + a1(x1-x0) = y1
## se rearranjar o a1 = (y1-y0)/(x1-x0)
## f(x2) = a0 + a1(x2-x0) + a2(x2-x0)(x2-x1) = y2
## se rearranjar o a2 = (y2-y1)/(x2-x1) - a1/(x2-x1) (o a1/(x2-x1) é o termo que já foi calculado e pode ser substituido)

import numpy as np


In [138]:
## f(x)=a0+a1(x−x0)+a2(x−x0)(x−x1)+⋯+an(x−x0)(x−x1)…(x−xn)
## por exemplo f(x0) = a0 = y0
## f(x1) = a0 + a1(x1-x0) = y1
## se rearranjar o a1 = (y1-y0)/(x1-x0)
## f(x2) = a0 + a1(x2-x0) + a2(x2-x0)(x2-x1) = y2
## se rearranjar o a2 = (y2-y1)/(x2-x1) - a1/(x2-x1) (o a1/(x2-x1) é o termo que já foi calculado e pode ser substituido)



def divided_diff(x, y):
    '''
    function to calculate the divided
    differences table
    '''
    n = len(y)
    tabela = np.zeros([n, n])


    # no exemplo 2 da apostila do tema 2
    # o vetor y eh [0.       1.386294] em numpy array, 0 EH O F(x1) e 1.386294 EH O F(x2) No material 
    # o vetor x eh [1 4] em numpy array, 0 EH O x1 e 1 EH O x2

    ## aqui ele pega todas as linhas da matriz, mas especifica a coluna 0 (primeira coluna) e atribui o valor de y
    ## entao fica assim:
    ## [[0.       0.      ] pode ver que a primeira coluna SAO OS MESMOS VALORES DE y
    ## [1.386294 0.      ]]

    tabela[:,0] = y

    
    ## tomando como base o exemplo 2 da apostila do tema 9
    ## for j in range(1, 2):        (O J NESSE CASO SO VAI VALER 1 PQ O RANGE COMECA NO 1 E VAI ATE 2 MAS NAO INCLUI O 2)
    ## for i in range(2 - 1):       (o range vai ser range(1), o i vai valer so 0)

    for j in range(1,n):
        for i in range(n-j):
            tabela[i][j] = (tabela[i+1][j-1] - tabela[i][j-1]) / (x[i+j]-x[i])
           

    # NA primeira iteracao de j, ele vai fazer o seguinte:
    # coef[0][1] = (coef[1][0] - coef[0][0]) / (x[1]-x[0]) = (1.386294 - 0) / (4-1) = 1,6094380.462098

    # dai a matriz coef ficou assim:
    # [[0.         0.462098]   (a primeira coluna sao os valores de y, a linha eh os valores dos coeficientes b1, b2, b3, etc)
    # [1.386294 0.       ]]
    
    print('tabela de diferenças divididas')
    print(tabela)
    print('\n')
    return tabela

def newton_poly(coef, x_data, x):
    '''
    evaluate the newton polynomial 
    at x
    '''
    n = len(x_data) - 1 
    p = coef[n]
    for k in range(1,n+1):
        p = coef[n-k] + (x -x_data[n-k])*p
    return p

In [129]:
x = np.array([1, 6])
y = np.array([0, 1.791759])
# get the divided difference coef
a_s = divided_diff(x, y)[0, :]  # o [0, :] pega a primeira linha da matriz
print(a_s)
# evaluate on new data points

y_new = newton_poly(a_s, x, 2)
print(y_new)


tabela de diferenças divididas
[[0.        0.3583518]
 [1.791759  0.       ]]


[0.        0.3583518]
0.3583518


In [130]:
x = np.array([1, 4, 6, 5])
y = np.array([0, 1.386294, 1.791759, 1.609438])
# get the divided difference coef
a_s = divided_diff(x, y)[0, :]  # o [0, :] pega a primeira linha da matriz
print(a_s)
# evaluate on new data points

y_new = newton_poly(a_s, x, 2)
print(y_new)


tabela de diferenças divididas
[[ 0.         0.462098  -0.0518731  0.0078654]
 [ 1.386294   0.2027325 -0.0204115  0.       ]
 [ 1.791759   0.182321   0.         0.       ]
 [ 1.609438   0.         0.         0.       ]]


[ 0.         0.462098  -0.0518731  0.0078654]
0.6287674


VEJA NESSE POLINOMIO DE ORDEM 3 QUE A TABELA DE DIFERENCAS DIVIDAS EH QUE NEM O EXEMPLO 4 DA AULA 9

E ENTENDA QUE A PRIMEIRA LINHA DESSA TABELA DE DIFERENCAS DIVIDIDAS EH OS COEFICIENTES B1, B2, B3, B4 DA FORMULA QUE ESTA NO MATERIAL 9


FINALMENTE O TRABALHO 14 REALMENTE

In [145]:

## COMO O POLINOMIO EH ORDEM 3 PEGA-SE 4 DADOS PARA USAR E ENCONTRAR OS COEFICIENTES


x = np.array([8, 9, 10, 11])
y = np.array([400, 900, 1500, 2250])
# get the divided difference coef
a_s = divided_diff(x, y)[0, :]  # o [0, :] pega a primeira linha da matriz
print(a_s)

y_new = newton_poly(a_s, x, 11.8)
print(y_new)




tabela de diferenças divididas
[[ 400.          500.           50.            8.33333333]
 [ 900.          600.           75.            0.        ]
 [1500.          750.            0.            0.        ]
 [2250.            0.            0.            0.        ]]


[400.         500.          50.           8.33333333]
2991.6000000000004


In [146]:
## COMO O POLINOMIO EH ORDEM 3 PEGA-SE 4 DADOS PARA USAR E ENCONTRAR OS COEFICIENTES


x = np.array([9, 10, 11, 12])
y = np.array([900, 1500, 2250, 3200])
# get the divided difference coef
a_s = divided_diff(x, y)[0, :]  # o [0, :] pega a primeira linha da matriz

y_new = newton_poly(a_s, x, 11.8)
print(y_new)


tabela de diferenças divididas
[[ 900.          600.           75.            8.33333333]
 [1500.          750.          100.            0.        ]
 [2250.          950.            0.            0.        ]
 [3200.            0.            0.            0.        ]]


2991.6000000000004


In [147]:

## COMO O POLINOMIO EH ORDEM 3 PEGA-SE 4 DADOS PARA USAR E ENCONTRAR OS COEFICIENTES


x = np.array([10, 11, 12, 13])
y = np.array([1500, 2250, 3200, 4400])
# get the divided difference coef
a_s = divided_diff(x, y)[0, :]  # o [0, :] pega a primeira linha da matriz

y_new = newton_poly(a_s, x, 11.8)
print(y_new)



tabela de diferenças divididas
[[1500.          750.          100.            8.33333333]
 [2250.          950.          125.            0.        ]
 [3200.         1200.            0.            0.        ]
 [4400.            0.            0.            0.        ]]


2991.600000000001
